<?php
    echo $this->partial('/partials/menu');
?>
<?php
$title = 'Deployments';
$this->headTitle($title);
?>
<h1><?php echo $this->translate($title); ?></h1>
<table class="table">
	<tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td align="center"><strong><?php echo $this->translate('Next step') ?></strong></td>
		<td align="center"><strong><a href="<?php echo $this->url('deployment') ?>
											?major=site_caption
											<?php if ($major == 'site_caption' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
			<?php echo $this->translate('Site');?></strong></td>
		<td align="center"><strong><a href="<?php echo $this->url('deployment') ?>
											?major=status
											<?php if ($major == 'status' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
			<?php echo $this->translate('Status');?></strong></td>
		<td align="center"><strong><a href="<?php echo $this->url('deployment') ?>
											?major=identifier
											<?php if ($major == 'identifier' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
			<?php echo $this->translate('Identifier');?></strong></td>
		<td align="center"><strong><a href="<?php echo $this->url('deployment') ?>
											?major=issue_date
											<?php if ($major == 'issue_date' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
			<?php echo $this->translate('Issue');?></strong></td>
		<td align="center"><strong><a href="<?php echo $this->url('deployment') ?>
											?major=retraction_limit
											<?php if ($major == 'retraction_limit' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
			<?php echo $this->translate('Retraction');?></strong></td>
		<td align="center"><strong><a href="<?php echo $this->url('deployment') ?>
											?major=management_date
											<?php if ($major == 'management_date' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
			<?php echo $this->translate('Management');?></strong></td>
		<td align="center"><strong><a href="<?php echo $this->url('deployment') ?>
											?major=current_hoped_delivery_date
											<?php if ($major == 'current_hoped_delivery_date' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
			<?php echo $this->translate('Hoped delivery');?></strong></td>
	</tr>
			
<?php foreach ($deployments as $deployment) : ?>
	<tr>
 		<td><a href="<?php echo $this->url('deployment/detail', array('id' => $deployment->id));?>"><img height="12" src="/images/zoom_plus_plain.png" alt="<?php echo $this->translate('detail') ?>" /></a></td>
		<td><a href="<?php echo $this->url('order/pdf', array('id' => $deployment->order_id));?>"><img height="12" src="/images/print.png" alt="<?php echo $this->translate('pdf') ?>" /></a></td>
	  	<td align="center"><a href="<?php echo $this->url('deploymentProduct/index', array('id' => $deployment->id));?>"><?php echo $this->translate('Rows') ?></a></td>
		<td align="center"><a href="<?php echo $this->url('deploymentWithdrawal/index', array('id' => $deployment->id));?>"><?php echo $this->translate('Withdrawals') ?></a></td>

<!--  Technical responsible -->
	<?php if ($current_role == 'resp_technique') : ?>
		<?php if ($deployment->status == 'A compléter') : ?>
			<td align="center"><a style="color: red" href="<?php echo $this->url('deploymentProduct/index', array('id' => $deployment->id));?>"><?php echo $this->translate('Complete') ?></a></td>
		<?php elseif ($deployment->status == 'Complété') : ?>
			<td align="center"><a href="<?php echo $this->url('deployment/transfer', array('id' => $deployment->id));?>"><?php echo $this->translate('Transfer') ?></a></td>
		<?php else : ?>
			<td>&nbsp;</td>
		<?php endif;?>

<!--  Deployment responsible -->
	<?php elseif ($current_role == 'resp_deploiement') : ?>
		<?php if ($deployment->status == 'Transféré') : ?>
			<td align="center"><a href="<?php echo $this->url('deployment/validate', array('id' => $deployment->id));?>"><?php echo $this->translate('Validate') ?></a></td>
		<?php elseif ($deployment->status == 'Validé' && $deployment->retraction_limit < Date('Y-m-d')) : ?>
			<td align="center"><a href="<?php echo $this->url('deployment/manage', array('id' => $deployment->id));?>"><?php echo $this->translate('Deploy') ?></a></td>
		<?php else : ?>
			<td>&nbsp;</td>
		<?php endif;?>

<!--  Others -->
	<?php else : ?>
		<td>&nbsp;</td>
	<?php endif; ?>

		<td align="center"><?php echo $deployment->site_caption ?></td>
		<td align="center"><?php echo $deployment->status ?></td>
		<td align="center"><?php echo $deployment->identifier ?></td>
		<td align="center"><?php echo $deployment->issue_date ?></td>
		<td align="center"><?php echo $deployment->retraction_limit ?></td>
		<td align="center"><?php echo $deployment->management_date ?>
		<td align="center"><?php echo $deployment->current_hoped_delivery_date ?>
	</tr>
<?php endforeach; ?>
</table>