<?php
    echo $this->partial('/partials/menu');
?>
<?php
$title = 'Equipements';
$this->headTitle($title);
?>
<h3><?php echo $this->translate($title); ?></h3>
<p><?php echo $this->translate('Order number').': '.$deployment->identifier ?></p>
<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('deploymentProduct/index', array('id' => $order->id)));
	$form->prepare();
	echo $this->form()->openTag($form);
?>
<table class="table">
	<tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
		<td colspan="13">
			<a href="<?php echo $this->url('deployment');?>"><?php echo $this->translate('Return to deployments') ?></a>&nbsp;&nbsp;|&nbsp;&nbsp;
			<a href="<?php echo $this->url('deploymentWithdrawal/index', array('id' => $deployment->id));?>"><?php echo $this->translate('Withdrawals') ?></a>
		</td>
	</tr>
	<tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		
		<td align="center"><strong><a href="<?php echo $this->url('deploymentProduct/index', array('id' => $order->id)) ?>
											?major=caption
											<?php if ($major == 'caption' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
			<?php echo $this->translate('Caption');?></strong></td>
		<td align="center"><strong><a href="<?php echo $this->url('deploymentProduct/index', array('id' => $order->id)) ?>
											?major=status
											<?php if ($major == 'status' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
			<?php echo $this->translate('Status');?></strong></td>
		<td align="center"><strong><a href="<?php echo $this->url('deploymentProduct/index', array('id' => $order->id)) ?>
											?major=availability_date
											<?php if ($major == 'availability_date' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
			<?php echo $this->translate('Availability date');?></strong></td>
		<td align="center"><strong><a href="<?php echo $this->url('deploymentProduct/index', array('id' => $order->id)) ?>
											?major=provisional_date
											<?php if ($major == 'provisional_date' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
			<?php echo $this->translate('Provisional date');?></strong></td>
		<td align="center"><strong><a href="<?php echo $this->url('deploymentProduct/index', array('id' => $order->id)) ?>
											?major=actual_date
											<?php if ($major == 'actual_date' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
			<?php echo $this->translate('Actual delivery');?></strong></td>
		<td align="center"><strong><a href="<?php echo $this->url('deploymentProduct/index', array('id' => $order->id)) ?>
											?major=connection_date
											<?php if ($major == 'connection_date' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
			<?php echo $this->translate('Connection date');?></strong></td>

		<td align="center"><strong><a href="<?php echo $this->url('deploymentProduct/index', array('id' => $order->id)) ?>
											?major=building
											<?php if ($major == 'building' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
			<?php echo $this->translate('Building');?></strong></td>
		<td align="center"><strong><a href="<?php echo $this->url('deploymentProduct/index', array('id' => $order->id)) ?>
											?major=floor
											<?php if ($major == 'floor' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
			<?php echo $this->translate('Floor');?></strong></td>
		<td align="center"><strong><a href="<?php echo $this->url('deploymentProduct/index', array('id' => $order->id)) ?>
											?major=department
											<?php if ($major == 'department' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
			<?php echo $this->translate('Department');?></strong></td>
	</tr>

<?php $sum = 0; $netSum = 0; ?>	
<?php foreach ($deploymentProducts as $deploymentProduct) : ?>
	<?php 
		$sum += $deploymentProduct->price;
		$net = $deploymentProduct->price + $deploymentProduct->option_price;
		$netSum += $net;
	 ?>
	<tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
	<?php if ($current_role == 'resp_deploiement' && $deployment->status == 'Pris en compte') : ?>
		<?php
			$element = $form->get('product'.$deploymentProduct->id);
		?>
        <td><?php echo $this->formElement($element) ?></td>
    <?php else : ?>
        <td>&nbsp;</td>
    <?php endif;?>
	<?php if ($current_role == 'resp_technique' && $deployment->status != 'Pris en compte') : ?>
    	<td align="center"><a href="<?php echo $this->url('deploymentProduct/update', array('id' => $deploymentProduct->id));?>"><img height="12" src="/images/edit_2.png" alt="<?php echo $this->translate('Update') ?>" /></a></td>
    <?php else : ?>
    	<td align="center"><a href="<?php echo $this->url('deploymentProduct/detail', array('id' => $deploymentProduct->id));?>"><img height="12" src="/images/zoom_plus_plain.png" alt="<?php echo $this->translate('Detail') ?>" /></a></td>
    <?php endif;?>
		<td align="center"><?php echo $deploymentProduct->caption ?></td>
		<td align="center"><?php echo $deploymentProduct->status ?></td>
		<td align="center"><?php echo $deploymentProduct->availability_date ?></td>
		<td align="center"><?php echo $deploymentProduct->provisional_date ?></td>
		<td align="center"><?php echo $deploymentProduct->actual_date ?></td>
		<td align="center"><?php echo $deploymentProduct->connection_date ?></td>
		<td align="center"><?php echo $deploymentProduct->building ?></td>
		<td align="center"><?php echo $deploymentProduct->floor ?></td>
		<td align="center"><?php echo $deploymentProduct->department ?></td>
		</tr>
<?php endforeach; ?>
<?php if ($current_role == 'resp_deploiement' && $deployment->status == 'Pris en compte') : ?>
	<!--  Check all  -->
	<tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
		<td colspan="13">
			<?php echo $this->formElement($form->get('check_all')) ?>&nbsp;&nbsp;
			<?php echo $this->translate('Select all') ?>
		</td>
	</tr>
	
	<!--  Batch update : availability_date -->
	<tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
	<?php
		$element = $form->get('update_availability_date');
		$element->setAttribute('class', 'btn btn-primary');
	?>
		<td colspan="5" align="right">
			<?php echo $this->formElement($element) ?>
		</td>
	<?php
		$element = $form->get('availability_date');
	?>
		<td colspan="9" align="left">
			<?php echo $this->formElement($element) ?>
		</td>
	</tr>
	
	<!--  Batch update : provisional_date -->
	<tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
	<?php
		$element = $form->get('update_provisional_date');
		$element->setAttribute('class', 'btn btn-primary');
	?>
		<td colspan="5" align="right">
			<?php echo $this->formElement($element) ?>
		</td>
	<?php
		$element = $form->get('provisional_date');
	?>
		<td colspan="9" align="left">
			<?php echo $this->formElement($element) ?>
		</td>
	</tr>
	
	<!--  Batch update : actual_date -->
	<tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
	<?php
		$element = $form->get('update_actual_date');
		$element->setAttribute('class', 'btn btn-primary');
	?>
		<td colspan="5" align="right">
			<?php echo $this->formElement($element) ?>
		</td>
	<?php
		$element = $form->get('actual_date');
	?>
		<td colspan="9" align="left">
			<?php echo $this->formElement($element) ?>
		</td>
	</tr>
	
	<!--  Batch update : connection_date -->
		<tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
	<?php
		$element = $form->get('update_connection_date');
		$element->setAttribute('class', 'btn btn-primary');
	?>
		<td colspan="5" align="right">
			<?php echo $this->formElement($element) ?>
		</td>
	<?php
		$element = $form->get('connection_date');
	?>
		<td colspan="9" align="left">
			<?php echo $this->formElement($element) ?>
		</td>
	</tr>

</table>
<?php endif;?>
<?php echo $this->form()->closeTag();?>

<script>
function checkAll() {
<?php foreach ($deploymentProducts as $deploymentProduct) :?>
	if (document.getElementById("check_all").checked) {
		document.getElementById("product<?php echo $deploymentProduct->id ?>").checked = true;
	}
	else {
		document.getElementById("product<?php echo $deploymentProduct->id ?>").checked = false;
	}
<?php endforeach;?>
}
</script>





<!--  Date picker script  -->


<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/jquery-ui.min.js"></script>
<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/themes/smoothness/jquery-ui.css" />
  <script>
  
  
  $.datepicker.regional['fr'] = {
    closeText: 'Fermer',
    prevText: 'Précédent',
    nextText: 'Suivant',
    currentText: 'Aujourd\'hui',
    monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'],
    monthNamesShort: ['Janv.','Févr.','Mars','Avril','Mai','Juin','Juil.','Août','Sept.','Oct.','Nov.','Déc.'],
    dayNames: ['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'],
    dayNamesShort: ['Dim.','Lun.','Mar.','Mer.','Jeu.','Ven.','Sam.'],
    dayNamesMin: ['D','L','M','M','J','V','S'],
    weekHeader: 'Sem.',
	dateFormat: 'yy-mm-dd',
    firstDay: 1,
    isRTL: false,
    showMonthAfterYear: false,
    yearSuffix: ''
};
$.datepicker.setDefaults($.datepicker.regional['fr']);
  
  
  
  
//  connection_date est l'id de  champ (connection date)

jQuery(document).ready(function($){
    $("#connection_date").datepicker();
});

//availability_date est l'id de  champ (availability date)
jQuery(document).ready(function($){
    $("#availability_date").datepicker();
});

//availability_date est l'id de  champ (provisional date)
jQuery(document).ready(function($){
    $("#provisional_date").datepicker();
});
  </script>